### ISSUE TITLE
Unable to make on ubuntu 20.02

### ISSUE THREAD

**Issue by ymulleneers** [cockpit-project/starter-kit#589]
Hello, 

I downloaded this project and tried to make it. I am not very experimented in NPM packaging.

```
sudo apt install npm
git clone https://github.com/cockpit-project/starter-kit.git
cd starter-kit/
make | tee log.log
```

It downloads a lot of NPM then dies in error as `follow`:
```
(...)
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for compression-webpack-plugin@9.2.0: wanted: {"node":">= 12.13.0"} (current: {"node":"10.19.0","npm":"6.14.4"})
(...)
[webpack-cli] Failed to load '/home/yves/tmp/starter-kit/webpack.config.js' config
[webpack-cli] /home/yves/tmp/starter-kit/node_modules/eslint-webpack-plugin/node_modules/jest-worker/build/index.js:110
  _ending;
         ^

SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/yves/tmp/starter-kit/node_modules/eslint-webpack-plugin/dist/getESLint.js:9:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
make: *** [Makefile:69 : dist/manifest.json] Erreur 2

```

How I can understand what the problem is ?  Are the WARN the problem?

**Comment by martinpitt** [comment]
> npm WARN notsup Unsupported engine for compression-webpack-plugin@9.2.0: wanted: {"node":">= 12.13.0"} (current: {"node":"10.19.0","npm":"6.14.4"})

This is the important message. Indeed several NPM modules just recently started to use features from a newer nodejs, which 20.04's old 10.x version does not support yet. I already sent #588 today to hack around that for building on RHEL/CentOS 8, but that will not help you for code development.

I'm afraid you'll have to get a newer nodejs from a third-party source (e.g. https://github.com/nodesource/distributions) or upgrade to Ubuntu 22.04 LTS.

**Comment by ymulleneers** [comment]
Thank you for you support.  Effectively, upgrading into LTS version have solved the issue.
