### ISSUE TITLE
Clarification regarding Software Versions in order to make the kit work

### ISSUE THREAD

**Issue by shantanoo-desai** [cockpit-project/starter-kit#693]
## Description

I have an Ubuntu 20.04.6 LTS where I wish to setup the starter-kit to develop for Cockpit. It turns out the standard package installations may not be compatible with the starter-kit.

As an example, for Ubuntu 20.04 LTS the core software versions are:

| Software | Version |
|--------|--------|
| `git` | `2.25.1` |
| `node` | `v10.19.0` |
| `npm`| `6.14.4` |
| `gettext` | `0.19.8.1` |

### Initial Setup

on the machine after installing the core dependencies, upon performing:

```bash
git clone https://github.com/cockpit-project/starter-kit && cd starter-kit && make
```

```bash
make: *** [Makefile:40: pkg/lib/cockpit-po-plugin.js] Error 129
```

will throw `error: unknown option no-write-fetch-head` for git as documented in #604 

Upon removing the `--no-write-fetch-head` from the `Makefile` lands up into another pit

```bash
/home/admin/starter-kit/build.js:3
import fs from 'node:fs';
       ^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
make: *** [Makefile:83: dist/manifest.json] Error 1
```

I am not sure what other potential changes I need to make to make it on _older_ distros which may not have updated software packages.

## Potential Solution

Maybe provide tabular information in the `README.md` as to which versions does the starter-kit work on.

**Comment by shantanoo-desai** [comment]
## Update

### Ubuntu 22.04.3 LTS

| Software | Version |
|--------|--------|
| `git` | `2.34.1` |
| `node` | `v12.22.9` |
| `npm`| `8.5.1` |
| `gettext` | `0.21` |

### Steps

upon cloning the repo and performing `make all` I am hit with the following error.

```bash
const esbuild = (await import(useWasm ? 'esbuild-wasm' : 'esbuild'));
                 ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
make: *** [Makefile:95: dist/manifest.json] Error 1
```
